FROM golang:1.10.2-alpine
COPY . /go/src/github.com/AntsEclipse/gochat
WORKDIR /go/src/github.com/AntsEclipse/gochat

RUN cd auth && go build .

FROM alpine:3.7 
COPY --from=0 /go/src/github.com/AntsEclipse/gochat/auth /auth
CMD ["./auth/auth"]
