version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: GoChat
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  

  cassandra:
    image: cassandra
    volumes:
      - ./kong:/var/lib/cassandra

  kong:
    image: kong
    restart: always
    environment:
      KONG_DATABASE: cassandra
      KONG_CASSANDRA_CONTACT_POINTS: cassandra
      cassandra_port: 9042
      KONG_CASSANDRA_PORT: 9042
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    depends_on:
      - cassandra
    volumes:
      - ./scripts:/usr/scripts
    command: bash -c "chmod +x /usr/scripts/wait.sh && ./usr/scripts/wait.sh cassandra:9042 -t 0 -- kong migrations up && ./usr/scripts/wait.sh cassandra:9042 -t 0 -- kong start"
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
      - "8444:8444"

  user:
    build:
      context: .
      dockerfile: ./dockerfile-user
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./user/user"
    depends_on:
      - auth
      - db

  auth:
    build:
      context: .
      dockerfile: ./dockerfile-auth
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./auth/auth"
    depends_on:
      - db
  
  register:
    build:
      context: .
      dockerfile: ./dockerfile-register
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./register/register"
    depends_on:
      - auth
      - db

  login:
    build:
      context: .
      dockerfile: ./dockerfile-login
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./login/login"
    depends_on:
      - auth
      - user
      - db

  chat:
    build:
      context: .
      dockerfile: ./dockerfile-chat
    restart: always
    command: ./chat/chat
    depends_on:
      - auth
      - db
