version: "3"
services:
  portainer:
    image: portainer/portainer
    volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - ./portainer:/data
    ports:
        - "9000:9000"

  reverse-proxy:
    image: traefik
    command: --api 
    ports:
      - "8000:8000"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: GoChat
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  user:
    build:
      context: .
      dockerfile: ./dockerfile-user
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./user/user"
    depends_on:
      - auth
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/user"
      - "traefik.backend=user"
      - "traefik.port=8080"

  auth:
    build:
      context: .
      dockerfile: ./dockerfile-auth
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./auth/auth"
    depends_on:
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/auth"
      - "traefik.backend=auth"
      - "traefik.port=8080"
  
  register:
    build:
      context: .
      dockerfile: ./dockerfile-register
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./register/register"
    depends_on:
      - auth
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/register"
      - "traefik.backend=register"
      - "traefik.port=8080"

  login:
    build:
      context: .
      dockerfile: ./dockerfile-login
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh db:5432 -t 0 -- ./login/login"
    depends_on:
      - auth
      - user
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/login"
      - "traefik.backend=login"
      - "traefik.port=8080"
  
  chat-redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  chat-cassandra1:
    image: cassandra
    volumes:
      - ./chatdata/c1:/var/lib/cassandra
      - ./chat/schema:/schemas
    ports:
      - "9042:9042"

  # chat-elasticsearch:
    # image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
    # ports:
     # - "9200:9200"
    # restart: always

  chat:
    build:
      context: .
      dockerfile: ./dockerfile-chat
    restart: always
    command: ./chat/chat
    depends_on:
      - auth
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/chat"
      - "traefik.backend=chat"
      - "traefik.port=8080"

  channels:
    build:
      context: .
      dockerfile: ./dockerfile-channels
    restart: always
    command: bash -c "chmod +x ./scripts/wait.sh && ./scripts/wait.sh chat-cassandra1:9042 -t 0 -- ./channels/channels"
    depends_on:
      - auth
      - db
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=PathPrefixStrip:/channels"
      - "traefik.backend=channels"
      - "traefik.port=8080"

